# -*- coding: utf-8 -*-

from . import account
from . import availability
from . import contact_request
from . import crm
from . import customer_type
from . import expense
from . import helpdesk
from . import hr
from . import ir_sequence
from . import item
from . import mail
from . import maintenance
from . import mrp
from . import parking
from . import partner
from . import payment
from . import pension
from . import product
from . import project
from . import purchase
from . import repair
from . import res_company
from . import res_config_settings
from . import res_country
from . import sale
from . import site
from . import stock
from . import sub_account
from . import vendor
